use "-no-install" for unit testing to ease test process. run unit testing under valgrind when the tool is available. fix unit testing torture.c (len of message) when the info line is provided. update the "missing" script.

diff --git a/src/test/tst b/src/test/tst
--- a/src/test/tst
+++ b/src/test/tst
@@ -10,38 +10,65 @@
 
 ok=0
 nok=0
+vok=0
+vnok=0
 total=0
 
+
 i=0
-while [ $i -lt 88 ]
+while [ -e $1/sip$i ]
 do
     filename=$1/sip$i
-   #mpatrol -C -S -L -d --list -p --use-debug ./torture_test $1/sip$i 0 $2
     ./torture_test $filename $2
+
     code=$?
-   if [ "$code" -eq 0 ]; then
-       ok=`expr $ok + 1`;
-   else
-       nok=`expr $nok + 1`
-   fi;
-   i=`expr $i + 1`
-   total=`expr $total + 1`
+    if [ "$code" -eq 0 ]; then
+	ok=`expr $ok + 1`;
+    else
+	nok=`expr $nok + 1`
+    fi;
+
+    if type "valgrind" > /dev/null; then
+        valgrind --tool=memcheck --leak-check=yes --leak-resolution=high --show-reachable=yes -q --error-exitcode=1 ./torture_test $filename $2 2>&1 
+
+	code=$?
+	if [ "$code" -eq 0 ]; then
+	    vok=`expr $vok + 1`;
+	else
+	    vnok=`expr $vnok + 1`
+	fi;
+    fi
+
+    i=`expr $i + 1`
+    total=`expr $total + 1`
 done
 
 i=0
-while [ $i -lt 13 ]
+while [ -e $1/sip-malformed$i ]
 do
     filename=$1/sip-malformed$i
-    #   #mpatrol -C -S -L -d --list -p --use-debug ./torture_test $1/sip-malformed$i 0 $2
     ./torture_test $filename $2
-   code=$?
-   if [ "$code" -eq 0 ]; then
-       ok=`expr $ok + 1`;
-   else
-       nok=`expr $nok + 1`
-   fi;
-   i=`expr $i + 1`
-   total=`expr $total + 1`
+
+    code=$?
+    if [ "$code" -eq 0 ]; then
+	ok=`expr $ok + 1`;
+    else
+	nok=`expr $nok + 1`
+    fi;
+
+    if type "valgrind" > /dev/null; then
+        valgrind --tool=memcheck --leak-check=yes --leak-resolution=high --show-reachable=yes -q --error-exitcode=1 ./torture_test $filename $2 2>&1 
+
+	code=$?
+	if [ "$code" -eq 0 ]; then
+	    vok=`expr $vok + 1`;
+	else
+	    vnok=`expr $vnok + 1`
+	fi;
+    fi
+
+    i=`expr $i + 1`
+    total=`expr $total + 1`
 done
 #
 
@@ -49,7 +76,9 @@ echo "unit testing total :   $total"
 echo "unit testing passed:   $ok"
 echo "unit testing failed:   $nok"
 
-
-
+if [ ! "$vnok" -eq 0 ]; then
+    echo "valgrind unit testing passed:   $vok"
+    echo "valgrind unit testing failed:   $vnok (valgrind + standard errors combined)"
+fi;
 
 
